### ISSUE TITLE
Module does not work with 2019.03.01

### ISSUE THREAD

**Issue by Skarsnik** [shuppet/p6-api-discord#31] opened 2019-04-01 10:00 UTC
I just try running the echo example to see if it was from my own script, but the example fails to work (sending a message back) and discord heartbeat is never replied after the first one.

**Comment by kawaii** [comment] 2019-04-01 10:11
Hi Skarsnik!

Can you double check the output of `perl6 --version` please? Here's what I get:
```
$ perl6 --version
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.
```
I'm using the RC2 release of Rakudo Star 2019.03 from [here](http://www.hankache.com/rakudostar/), though I'm not sure if it makes much difference, either way - the examples all seem to work fine for me. :(

![image](https://user-images.githubusercontent.com/12242877/55320398-e06ebc00-546e-11e9-87b0-f74626e7d474.png)

**Comment by Skarsnik** [comment] 2019-04-01 10:13
skarsnik@DESKTOP-UIA12T1:/mnt/f/Project/Gobbla$ ../Perl6/benchmark/rakudo-2019.03.1/install/bin/perl6 --version
This is Rakudo version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

skarsnik@DESKTOP-UIA12T1:/mnt/f/Project/Gobbla$ ../Perl6/benchmark/rakudo-2019.03.1/install/bin/perl6 ../Perl6/p6-api-dscord/examples/echo-server.p6 <token>
« ♥
» ♥
« ♥
« ♥
Heartbeat wasn't acknowledged! ☹
Attempting to reconnect...
Resuming session 96c4fe251c3bffd186b462ae8b7ee8d0 at sequence 2

**Comment by kawaii** [comment] 2019-04-01 10:16
Looks like you could be suffering as a result of https://github.com/croservices/cro-websocket/issues/15, which is something we're still unable to fix or debug ourselves. We sometimes run into this issue a lot (for hours and hours on end) and other days the library will work flawlessly (with no difference in network connection, environment and compiler version). :(

**Comment by Skarsnik** [comment] 2019-04-01 20:28
Duh, as you say, it works this evening ><

**Comment by kawaii** [comment] 2019-04-01 21:00
I bugged @Altai-man about it earlier today and he said he'll try and think of a proposal to fix the underlying issue in Cro::WebSocket, so hopefully in a coming release we might see it resolved (or even a hot-patch would be nice :wink:).

**Comment by Altai-man** [comment] 2019-04-01 22:22
@kawaii I have looked at the state of the things briefly tonight and reproduced both issues mentioned in the ticket with https://gist.github.com/Altai-man/33b94415598ffca6114f7f16c53aa93b
I'll try to get down these two I am sure about.

Please, write if one of these happens to be similar to the persistent issue you are having with this module.

**Comment by kawaii** [comment] 2019-07-08 14:35
Looks like this is probably resolved by now, please open a new issue if the problem occurs in the future.

**Closed by kawaii** 2019-07-08 14:35 UTC
Labels: bug, help wanted

**Comment by Skarsnik** [comment] 2019-07-09 08:40
I updated Cro and so far so good :)
